BACON:
	javac BACON/*.java

test:
	javac -cp .:test/junit-4.8.1.jar test/*.java
# to run tests, use java -cp .:test/junit-4.8.1.jar org.junit.runner.JUnitCore test/<test files>
#
# Mike's note: For windows:
# Compile tests: javac -cp .;test/junit-4.8.1.jar test/*.java
# Run tests: java -cp .:test/junit-4.8.1.jar org.junit.runner.JUnitCore test.<ClassNameTest>